### ISSUE TITLE
KeyError: 'face_morpher'

### ISSUE THREAD

**Issue by Lisawu12138** [pkhungurn/talking-head-anime-3-demo#12]
Hi! When I run it, it says that there's an error for Network.face_morpher.
I will put my traceback here! 
Sorry for the bother though

Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 327, in update_result_image_bitmap
    output_image = self.poser.pose(self.torch_source_image, pose)[0].float()
  File "F:\Anime3\tha3\poser\general_poser_02.py", line 61, in pose
    output_list = self.get_posing_outputs(image, pose)
  File "F:\Anime3\tha3\poser\general_poser_02.py", line 76, in get_posing_outputs
    return self.output_list_func(modules, batch, outputs)
  File "F:\Anime3\tha3\poser\modes\standard_float.py", line 69, in func
    output = self.get_output(Branch.all_outputs.name, modules, batch, outputs)
  File "F:\Anime3\tha3\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "F:\Anime3\tha3\poser\modes\standard_float.py", line 128, in compute_output
    editor_output = self.get_output(Network.editor.outputs_key, modules, batch, outputs)
  File "F:\Anime3\tha3\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "F:\Anime3\tha3\poser\modes\standard_float.py", line 115, in compute_output
    input_original_image = self.get_output(Branch.face_morphed_full.name, modules, batch, outputs)[0]
  File "F:\Anime3\tha3\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "F:\Anime3\tha3\poser\modes\standard_float.py", line 100, in compute_output
    face_morpher_output = self.get_output(Network.face_morpher.outputs_key, modules, batch, outputs)
  File "F:\Anime3\tha3\compute\cached_computation_protocol.py", line 19, in get_output
    output = self.compute_output(key, modules, batch, outputs)
  File "F:\Anime3\tha3\poser\modes\standard_float.py", line 98, in compute_output
    return modules[Network.face_morpher.name].forward(input_image, face_pose)
KeyError: 'face_morpher'

**Comment by dragonmeteor** [comment]
Have you downloaded the models?
https://github.com/pkhungurn/talking-head-anime-3-demo#download-the-models
