### ISSUE TITLE
pip install wxpython fails during setup on Ubuntu 20.04 on WSL2 

### ISSUE THREAD

**Issue by YUzushio** [pkhungurn/talking-head-anime-3-demo#2]
When setting up this repository on Ubuntu 20.04 OS on WSL2
`pip install wxpython`.
error occurs when executing it.

##  environment

-WLS2 (Windows 11)
- OS: Ubuntu 20.04
- Python Version: 3.9.2
- Anaconda Version: 4.12.0
- GPU: RTX 3080
- NVIDIA-SMI 515.43.01
- Driver Version: 516.01
- CUDA Version: 11.7

## Error detail

1.  C++ compiler not found
2. GTK+ library not found
(The actual error text is attached, reproduced later, as I have deleted the prompts from the encounter.)

## temporary solution in local

Run the following two commands before running `pip install wxpython`

- `sudo apt install -y build-essential`
- `sudo apt install -y libgtk-3-dev`

## impression
I got hooked because I was in the habit of executing and developing code in WSL2 and Docker containers instead of on Windows 11 on a regular basis.
This was a rare case where a C++ compiler (and other development libraries) was not included in my WSL2 Linux.
However, some people may get caught, so I created an Issue.

I am creating this Issue because the README is very thorough and I thought it might be a good idea to mention this case.

Is it possible that it was never intended to run on WSL2 Linux ...?
At any rate, I put Anaconda directly into Windows 11 and ran it in a straightforward manner and it worked fine.

This tool is too nice for words... Thank you for developing it!

**Comment by YUzushio** [comment]
Here, error message(Sorry to late).

```
(talking-head-anime-3-demo) root@ae7e2ca29589:/# pip install wxpython
Collecting wxpython
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-378x8iw8/wxpython_f93cb77925a644389ea53972b7695ca3/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-378x8iw8/wxpython_f93cb77925a644389ea53972b7695ca3/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(talking-head-anime-3-demo) root@ae7e2ca29589:/# 
```
