### ISSUE TITLE
KeyError when load ifacialmocap

### ISSUE THREAD

**Issue by YuzhouPeng** [pkhungurn/talking-head-anime-3-demo#25]
Hello, when I use ifacialmocap to connect computer, error happens:

Error 1:
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 280, in update_capture_panel
    value = data[rotation_name]
KeyError: 'rightEyeBoneX'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 312, in update_result_image_bitmap
    current_pose = self.pose_converter.convert(ifacialmocap_pose)
  File "/media/test/DATA/talking-head-anime-3-demo/tha3/mocap/ifacialmocap_poser_converter_25.py", line 282, in convert
    (ifacialmocap_pose[MOUTH_SMILE_LEFT] + ifacialmocap_pose[MOUTH_SMILE_RIGHT]) / 2.0 \
KeyError: 'mouthSmileLeft'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 280, in update_capture_panel
    value = data[rotation_name]
KeyError: 'rightEyeBoneX'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 312, in update_result_image_bitmap
    current_pose = self.pose_converter.convert(ifacialmocap_pose)
  File "/media/test/DATA/talking-head-anime-3-demo/tha3/mocap/ifacialmocap_poser_converter_25.py", line 282, in convert
    (ifacialmocap_pose[MOUTH_SMILE_LEFT] + ifacialmocap_pose[MOUTH_SMILE_RIGHT]) / 2.0 \
KeyError: 'mouthSmileLeft'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 280, in update_capture_panel
    value = data[rotation_name]
KeyError: 'rightEyeBoneX'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 312, in update_result_image_bitmap
    current_pose = self.pose_converter.convert(ifacialmocap_pose)
  File "/media/test/DATA/talking-head-anime-3-demo/tha3/mocap/ifacialmocap_poser_converter_25.py", line 282, in convert
    (ifacialmocap_pose[MOUTH_SMILE_LEFT] + ifacialmocap_pose[MOUTH_SMILE_RIGHT]) / 2.0 \
KeyError: 'mouthSmileLeft'
Traceback (most recent call last):
  File "tha3/app/ifacialmocap_puppeteer.py", line 280, in update_capture_panel
    value = data[rotation_name]
KeyError: 'rightEyeBoneX'

Error 2: after I can see the value. when I load image, the program just stuck. 

But when I run manual_poser.py, I can load image and modify it.

Can you tell me how to solve it? thank you

**Comment by BruceXu2021** [comment]
Hello, have you solved this problem
